name: build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Environment variables
      run: |
        echo "Run ID = ${{ github.run_id }}"
        echo "Run Number = ${{ github.run_number }}"
        echo "Event Name = ${{ github.event_name }}"
        echo "Ref = ${{ github.ref }}"
        echo "Head Ref = ${{ github.head_ref }}"
        echo "Base Ref = ${{ github.base_ref }}"
        echo "Workspace = ${{ github.workspace }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --nologo
    - name: Test
      run: dotnet test --no-build --configuration Release --nologo
    - name: Pack
      run: dotnet pack --output ./artifacts --no-build --configuration Release --nologo
    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
