name: Publish

on: workflow_dispatch

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet restore ./src/All/All.csproj

    - name: Build
      run: dotnet build --no-restore --configuration Release --nologo

    - name: Test
      run: dotnet test --no-build --configuration Release --nologo

    - name: Pack
      run: dotnet pack --output ./artifacts --no-build --configuration Release --nologo --version-suffix build${{ github.run_number }}

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          ./artifacts
          !**/*.snupkg

    - name: Publish
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
